### ISSUE TITLE
osa4_02. EnsimmäinenTilisiirtosi - virheilmoitus palautuksen yhteydessä

### ISSUE THREAD

**Issue by TeroPesonen** [rage/ohjelmointi-20#28]
Tehtävän palautuksen yhteydessä virheilmoitus

---
Unable to run tests because this course's teacher has not configured this exercise template correctly. Please contact your teacher so that they can fix the template and rerun your submission. If your solution is correct, you'll get the points from this exercise once the teacher reruns your submission.

**Comment by Kanis757** [comment]
Mullakin sama ongelma.

Unable to run tests because this course's teacher has not configured this exercise template correctly. Please contact your teacher so that they can fix the template and rerun your submission. If your solution is correct, you'll get the points from this exercise once the teacher reruns your submission.

**Comment by nygrenh** [comment]
Kiitos ilmoituksesta! Korjasin ongelman ja laitoin palautukset uudelleen tarkistettavaksi eli oikeista vastauksista olisi pitänyt tulla pisteet.

**Comment by Kanis757** [comment]
Kiitos nopeasta vastauksesta :) Nyt se toimii, sain pisteet!

**Comment by TeroPesonen** [comment]
Kiitokset.

 

Minulla olisi vieno erillispyyntö. Olisiko osioiden julkistusta mahdollista aikaistaa aamulle? 

 

Minulle ja varmaan monelle muullekin työssäkäyvällä lauantai on siivous- ja pyykkäyspäivän lisäksi viikon primääri opiskelupäivä. Tällöin heti herättyään pääsisi tehtäviin käsiksi.

 

Kiitokset etukäteen pyynnön ottamisesta harkintaan.

 

Parhain terveisin

 

Tero
